name: Build
on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install nixos-generators
        run: |
          nix profile install github:nix-community/nixos-generators
      - name: Build
        run: |
          ./reimg build
      - name: Compress
        run: |
          xz -T 0 -c -z result/nixos.img > ReImg.img.xz
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ReImg.img.xz
