name: Build
on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          ./reimg build
      - name: Compress
        run: |
          xz -T 0 -c -z result/nixos.img > ReImg.img.xz
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ReImg.img.xz
